{% set name = "pyiron_potentialfit" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_potentialfit-{{ version }}.tar.gz
  sha256: edefa4b05245d62ae705e041f7fdb802780955f79f9cffcfd3846e7ffccbd96b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ase >=3.22.1
    - pyiron_atomistics >=0.3.4
    - matplotlib-base >=3.8.0
    - numpy >=1.26.0
    - pyiron_base >=0.6.7
    - scipy >=1.11.3

test:
  imports:
    - pyiron_potentialfit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_potentialfit
  summary: Fitting machine learning interatomic potentials with pyiron.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
