{% set name = "pyiron_potentialfit" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_potentialfit-{{ version }}.tar.gz
  sha256: a06f725c8519f53f1f962702e464266af61e8618707aacdb46d56af407d20e99

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - dill
    - seaborn
    - runnerase >=0.3.3
    - python >=3.8
    - ase >=3.22.1
    - pyiron_atomistics >=0.5.1
    - matplotlib-base >=3.8.3
    - numpy >=1.26.4
    - pyiron_base >=0.8.1
    - scipy >=1.11.4

test:
  imports:
    - pyiron_potentialfit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_potentialfit
  summary: Fitting machine learning interatomic potentials with pyiron.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
