{% set name = "pyiron_potentialfit" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_potentialfit-{{ version }}.tar.gz
  sha256: 0da1aa763a7f43f0564fc6dc9633d08ccf7d018ae1fe482cf7d4580897bf12af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - runnerase >=0.3.3
    - python >=3.8
    - ase >=3.22.1
    - pyiron_atomistics >=0.4.16
    - matplotlib-base >=3.8.3
    - numpy >=1.26.4
    - pyiron_base >=0.7.9
    - scipy >=1.11.4

test:
  imports:
    - pyiron_potentialfit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_potentialfit
  summary: Fitting machine learning interatomic potentials with pyiron.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
